### PR TITLE
CMake Migration

### PR DESCRIPTION
**Pull request by chutchinson**
Migrated to a CMake-based build system for future development. Added MPL license headers to all relevant source files. Moved all source code to rpgtoolkit namespace. Replaced Visual Studio pragma in headers with standard header guard. Compiler support for gcc 4.x.

NOTE: This is a pretty large PR that encompasses many changes to migrate to a multi-project layout with a CMake-based build system (http://www.cmake.org/). Almost every source file was touched with the following modifications: standard header guard (instead of #pragma once), namespace changed to rpgtoolkit, and a license boilerplate. Additionally, I propose use of the Mozilla Public License 2.0 (MPLv2).

### CODE REVIEW

**Comment by chutchinson** [comment]
If MPLv2 is not desirable feel free to reject this PR and we can hopefully discuss an alternative license.

**Comment by chutchinson** [comment]
Also, this PR supports compilation under Windows with MSYS2/MinGW and GCC 4.9.x.

**Comment by mariobadr** [comment]
Oops, didn't see this option to leave a comment. And now I see how to merge the pull request. Chris I sent you an email via your website.

**Comment by chutchinson** [comment]
I replied with a justification for MPLv2. CMake probably deserves a justification, but I would encourage personal research and consideration. It allows us to separate the project from the build tools (e.g. Visual Studio) so we can allow other compilers, development environments, toolchains, platforms, etc.

**Comment by mariobadr** [comment]
I accepted the request but don't see a CMakeLists file?

**Comment by chutchinson** [comment]
Oops! Looks like it was being omitted due to the .gitignore... revert the PR and I will make the necessary commits.

**Pull request merged**
