### PR TITLE
CMake Migration

### PR DESCRIPTION
**Pull request by chutchinson**
Fixes issues with previous PR

### CODE REVIEW

**Comment by chutchinson** [comment]
Oops looks like it only merged the build files...

**Comment by mariobadr** [comment]
Is there a way to give you co-ownership of the repo?

**Comment by chutchinson** [comment]
On the repository page (right side) -> Settings -> Collaborators

**Comment by mariobadr** [comment]
Done, thanks :)

**Comment by mariobadr** [comment]
Hey Euix,

So here's what I'm trying to do: I want to separate out some code from the
RPG Toolkit into my "Clio Game Framework" library (you can find it here:
https://github.com/mariobadr/Clio). Clio is meant to be generic enough for
any 2D game and uses SDL2. Clio has classes that handle creating the
window, 2D renderer, input management via callbacks, game state stack, et
cetera. Then, Trans4 uses Lua + Clio to create an RPG Engine. This is where
the asset pipeline and such go as well as the interface between Lua and
functions provided by the RPG Toolkit. I've drawn a shitty diagram for you
(attached). I've tried mimicing your CMakeLists file but I'm failing at the
point of making clio into a static library...

As for simplifying the build system, I was going to show step-by-step how
to compile each dependence and get it to run with the TK. It took me a few
minutes to get it myself, and there are some pitfalls even when using the
GUI.


Mario

**Comment by chutchinson** [comment]
Marz,

To make a static library you essentially need to replace add_executable with add_library, as mentioned by the following documentation:

http://www.cmake.org/cmake/help/v3.0/command/add_library.html

For example:

add_library("clio" STATIC "System.c" "SystemSettings.c")

... would create a static library (clio.lib) with the specified source files. I suppose I could commit to the game framework too - it's integral to the engine anyway.

**Pull request merged**
